<a href="https://colab.research.google.com/github/himanigupta1007/SHALA2020/blob/master/Assignment_1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [3]:
import numpy as np
a=np.random.random((3,5))
b=np.random.random_sample((3,5))
print('a={}'.format(a))
print('b={}'.format(b))

a=[[0.50087064 0.67463811 0.2750197  0.60623722 0.47612509]
 [0.46831561 0.77201229 0.10878588 0.84838929 0.85060899]
 [0.02268713 0.71825102 0.24802525 0.42770018 0.30012905]]
b=[[0.48787368 0.18705934 0.9836852  0.2061093  0.52505672]
 [0.9109171  0.89153099 0.81817242 0.09649635 0.02494   ]
 [0.12084163 0.34751825 0.05613426 0.86863286 0.18554029]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all non-negative integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [10]:
c=np.arange(100)
print('c={}'.format(c))
d=np.zeros((3,3),dtype=int)
print('d={}'.format(d))




c=[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
d=[[0 0 0]
 [0 0 0]
 [0 0 0]]


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [11]:
e = [[1,2,3],[4,5,6],[7,8,9]]
print('numpy array of e={}'.format(np.array(e)))



numpy array of e=[[1 2 3]
 [4 5 6]
 [7 8 9]]


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [15]:
f=np.ones((5,5),dtype=int)
print('f={}'.format(f))
g=np.eye((5),dtype=int)
print('g={}'.format(g))

f=[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
g=[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $c^\prime$ and print **YES** when the shapes of $c$ and $c^\prime$ are same. Otherwise print **NO**.

In [54]:
h=np.reshape(c,(10,10))
c1=h.flatten()
if c.shape==c1.shape:
  print("YES")
else:
  print("NO")


YES


Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [25]:
A = np.random.rand(2,10,5)
A1=np.transpose(A,(2,0,1))
print('Transpose of A={}'.format(A1))


[[[0.27590267 0.9250609  0.11183718 0.6754143  0.82346346]
  [0.22518307 0.71154607 0.85763848 0.73708366 0.68775835]
  [0.97344761 0.01677675 0.0726611  0.24587759 0.89852364]
  [0.56056922 0.75181003 0.38347816 0.65766174 0.33189785]
  [0.45636441 0.02679889 0.87650424 0.7071456  0.14498312]
  [0.52383617 0.10661877 0.36935621 0.58616704 0.27928866]
  [0.77918251 0.20347945 0.29892765 0.42876514 0.57302843]
  [0.93232379 0.14250228 0.74896721 0.36460302 0.23760851]
  [0.72735072 0.66688421 0.74661812 0.0305728  0.64328716]
  [0.24264955 0.31070686 0.17549077 0.94301439 0.97605599]]

 [[0.29556221 0.68289288 0.78109875 0.13103938 0.2625344 ]
  [0.55539888 0.3268016  0.90080024 0.84878703 0.03540416]
  [0.77169716 0.03600187 0.09962764 0.78849819 0.58559026]
  [0.96388497 0.09666075 0.28028004 0.77067887 0.76615011]
  [0.51589138 0.27839517 0.14266745 0.00305549 0.7162929 ]
  [0.48554652 0.68549935 0.85457773 0.75290721 0.87120038]
  [0.96948536 0.89922761 0.06507952 0.0977724  0.49349

You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [28]:
np.random.seed(0)
X = np.random.rand(10,5)
print('min[X]={} and argmin[X]={} for each column'.format(np.min(X,0),np.argmin(X,0)))
print('max[X]={} and argmax[X]={} for each column'.format(np.max(X,0),np.argmax(X,0)))
print('min[X]={} and argmin[X]={} for each row'.format(np.min(X,1),np.argmin(X,1)))
print('max[X]={} and argmax[X]={} for each row'.format(np.max(X,1),np.argmax(X,1)))
print('min[X]={} and argmin[X]={} for entire matrix'.format(np.min(X),np.argmin(X)))
print('max[X]={} and argmax[X]={} for entire matrix'.format(np.max(X),np.argmax(X)))



min[X]=[0.0871293  0.0202184  0.1289263  0.06022547 0.0187898 ] and argmin[X]=[3 3 9 8 6] for each column
max[X]=[0.97861834 0.79915856 0.94466892 0.96366276 0.87001215] and argmax[X]=[4 4 5 1 3] for each column
min[X]=[0.4236548  0.38344152 0.07103606 0.0202184  0.11827443 0.14335329
 0.0187898  0.61209572 0.06022547 0.1289263 ] and argmin[X]=[4 4 4 1 4 1 4 1 3 2] for each row
max[X]=[0.71518937 0.96366276 0.92559664 0.87001215 0.97861834 0.94466892
 0.77423369 0.94374808 0.6976312  0.67063787] and argmax[X]=[1 3 3 4 0 2 1 3 2 0] for each row
min[X]=0.018789800436355142 and argmin[X]=34 for entire matrix
max[X]=0.978618342232764 and argmax[X]=20 for entire matrix


Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

In [31]:
print('mean={} of each row'.format(np.mean(X,1)))
print('mean={} of each column'.format(np.mean(X,0)))
print('Standard deviation={} of each row'.format(np.std(X,1)))
print('Standard deviation={} of each column'.format(np.std(X,0)))
print('mean={} of entire matrix'.format(np.mean(X)))
print('Standard deviation={} of entire matrix'.format(np.std(X)))



mean=[0.56706085 0.66447172 0.57705944 0.51762729 0.62761197 0.5328907
 0.41643268 0.69444672 0.44423265 0.33781717] of each row
mean=[0.56044382 0.46781457 0.62009909 0.64025127 0.40121685] of each column
Standard deviation=[0.09445299 0.23322986 0.29189733 0.38052993 0.30431633 0.26338419
 0.25841437 0.12727959 0.23169975 0.18537332] of each row
Standard deviation=[0.24687647 0.25752158 0.22948615 0.28054144 0.26584905] of each column
mean=0.5379651182755409 of entire matrix
Standard deviation=0.27226582292177587 of entire matrix


Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [46]:
np.random.seed(3)
Y = np.random.rand(10,10)
print('det={}'.format(np.linalg.det(Y)))
print('rank={}'.format(np.linalg.matrix_rank(Y)))
print('diagonal={}'.format(np.diag(Y)))
print('trace={}'.format(np.trace(Y)))
eigen_values,eigen_vectors=np.linalg.eig(Y)
print('eigen_values={}'.format(eigen_values))
print('matrices={} after singular values decomposition'.format(np.linalg.svd(Y)))
print('inverse={} \n and:\n pseduo-inverse={}'.format(np.linalg.inv(Y),np.linalg.pinv(Y)))
print('multiplication of Y with X={}'.format(np.dot(Y,X)))
inv_Y=np.linalg.pinv(Y)
print('multiplication of Y with its inverse={}'.format(np.dot(Y,inv_Y)))


det=-0.012807808169095483
rank=10
diagonal=[0.5507979  0.45683322 0.44045372 0.84575087 0.4576864  0.36217621
 0.06152893 0.19897603 0.92672568 0.19638058]
trace=4.497309545724899
eigen_values=[ 4.797525  +0.j          0.72411408+0.52238181j  0.72411408-0.52238181j
 -0.48250062+0.55413671j -0.48250062-0.55413671j -0.6909002 +0.j
 -0.25905659+0.32357377j -0.25905659-0.32357377j  0.2127855 +0.08352477j
  0.2127855 -0.08352477j]
matrices=(array([[-0.31776408, -0.02455508, -0.60644878, -0.17883359, -0.12672161,
         0.14873878, -0.17823942, -0.52859453, -0.02295855, -0.38570883],
       [-0.26118514, -0.10864541, -0.24911354,  0.26547359,  0.52168399,
        -0.25773901, -0.46995326,  0.21752636, -0.39285046,  0.16234491],
       [-0.31347907, -0.34483471, -0.25292297,  0.1214296 ,  0.1486964 ,
         0.33436315,  0.54080229,  0.48017168,  0.05660692, -0.20966421],
       [-0.35815379,  0.59490017,  0.30255161,  0.15850614, -0.11046295,
         0.3051409 ,  0.07395537,  0.03044889,

## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [51]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"
Titanic3=pd.read_csv("http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv")
print(Titanic3)
Titanic3.head(5)



      pclass  survived  ...   body                        home.dest
0          1         1  ...    NaN                     St Louis, MO
1          1         1  ...    NaN  Montreal, PQ / Chesterville, ON
2          1         0  ...    NaN  Montreal, PQ / Chesterville, ON
3          1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4          1         0  ...    NaN  Montreal, PQ / Chesterville, ON
...      ...       ...  ...    ...                              ...
1304       3         0  ...  328.0                              NaN
1305       3         0  ...    NaN                              NaN
1306       3         0  ...  304.0                              NaN
1307       3         0  ...    NaN                              NaN
1308       3         0  ...    NaN                              NaN

[1309 rows x 14 columns]


pclass  survived  ...   body                        home.dest
0       1         1  ...    NaN                     St Louis, MO
1       1         1  ...    NaN  Montreal, PQ / Chesterville, ON
2       1         0  ...    NaN  Montreal, PQ / Chesterville, ON
3       1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4       1         0  ...    NaN  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---





---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



###Normalization


---



1. Normalize the columns which have numerical data



---





---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

In [0]:
import matplotlib.pyplot as plt

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.